modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="ufm"
version="${file.jarVersion}"
displayName="Unimplemented Features Mod "
logoFile="examplemod.png"
credits="Most of the ideas were mine, but some textures don't. The original textures rights go to their respective games that are owned by Mojang."
authors="Mr_SuitedWolf"
description='''
Adds a lot of funky things. Enjoy!
'''

[[dependencies.ufm]] 
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ufm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"